name: Deploy Databricks Jobs

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  PIP_NO_INPUT: "1"

jobs:
  deploy-job:
    if: (github.event_name == 'workflow_dispatch') || (github.event.pull_request.merged == true)
    runs-on: uhg-runner
    permissions:
      contents: read
    env:
      DATABRICKS_AUTH_TYPE: azure-client-secret
      DATABRICKS_HOST: https://adb-3239959380256842.2.azuredatabricks.net/
      ARM_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.DATABRICKS_TENANT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v6
        env:
          PIP_INDEX_URL: https://${{ secrets.JFROG_User }}:${{ secrets.JFROG_Token }}@edgeinternal1uhg.optum.com/artifactory/api/pypi/glb-pypi-vir/simple
          PIP_EXTRA_INDEX_URL: https://${{ secrets.JFROG_User }}:${{ secrets.JFROG_Token }}@centraluhg.jfrog.io/artifactory/api/pypi/glb-pypi-vir/simple
        with:
          python-version: '3.12'

      - name: Install build dependencies
        env:
          PIP_INDEX_URL: https://${{ secrets.JFROG_User }}:${{ secrets.JFROG_Token }}@edgeinternal1uhg.optum.com/artifactory/api/pypi/glb-pypi-vir/simple
          PIP_EXTRA_INDEX_URL: https://${{ secrets.JFROG_User }}:${{ secrets.JFROG_Token }}@centraluhg.jfrog.io/artifactory/api/pypi/glb-pypi-vir/simple
        run: pip install hatchling

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@v1.5.0

      - name: Validate Databricks bundle
        run: databricks bundle validate -t prod

      - name: Deploy Databricks bundle
        run: databricks bundle deploy -t prod
